### ISSUE TITLE
Deno runtime support

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#1322]
## Type of Change

Feature

## Summary

Splitting of from https://github.com/ProjectEvergreen/greenwood/issues/953 and based on some initial prototyping being conducted [here](https://github.com/ProjectEvergreen/greenwood-demo-adapter-deno-deploy/pull/1), it seems like there should be a path towards basic Deno support for Greenwood. 

What does that mean in pratice?  Effectively instead of using npm and node, leverage the equivalents in Deno
```sh
$ deno install
$ deno task dev # maps to `greenwood dev`
```

## Details

Some of the main considerations to account for as part of this work

1. Figure out why `greenwood develop` is showing a blank page
1. Seems like we'll need a standalone issue to prefix node_modules with `npm:` and NodeJS built-ins with `node:` - https://github.com/ProjectEvergreen/greenwood/issues/1324
1. 🚨 Deno won't be able to support custom loaders - https://github.com/denoland/deno/issues/1739
1. Validate Deno deploy support
1. Include a GitHub action to validate all test cases during Greenwood CI
1. Add documentation to the Greenwood website

----

Deno now supports CSS Module Scripts!
https://deno.com/blog/v2.9#css-module-imports

**Comment by thescientist13** [comment]
Deno now has support for custom loaders, using Node's module hooks implementation (and a lot of recent Node compat enhancements)!  👀 
https://deno.com/blog/v2.8#module-loader-hooks

Probably worth revisiting this again and seeing how far we can get now.

**Comment by thescientist13** [comment]
Seeing the same Bun issue we had
- https://github.com/thescientist13/greenwood-deno/pull/2
- https://github.com/ProjectEvergreen/greenwood/pull/1577

**Comment by thescientist13** [comment]
So with the news that Deno now supports custom loaders](https://deno.com/blog/v2.8#module-loader-hooks), I've been playing around running [Greenwood on Deno and Deno Deploy](https://github.com/thescientist13/greenwood-deno) and have made some significant progress!  I think we have a pretty good pathway to start landing changes to support this 🥳 

I do want to do a [Lit SSR test](https://github.com/thescientist13/greenwood-lit-ssr) first, but I think if we can land what we have below, I think we will have a "complete" enough experience to make it officially supported 🤞 

**Deno Support**
1. [x] Refine node_modules serving support (same issue happened with Bun) - https://github.com/ProjectEvergreen/greenwood/pull/1577
1. [x] we will need to adopt #1005 per https://github.com/thescientist13/greenwood-deno/pull/10/changes#diff-1cdece70a4ac7fa6de6cbe472c9b062c4d838acef22a567b5b470d1c1561a508R5
1. [x] API handlers that don't use `async` cause a deno-lint rule exception, but break without the `async` keyword if the function is not async? - looks like it [works just fine](https://github.com/thescientist13/greenwood-deno/pull/10/changes/e171fd766631e5bc3616bed5ed522ba4f8d6f619)!
1. [x] For [custom loaders](https://github.com/thescientist13/greenwood-deno/pull/5), we will need to refactor Greenwood to use the new [`registerHooks` API](https://nodejs.org/api/module.html#moduleregisterhooksoptions) as the `register` based API is deprecated.  This will also require Greenwood handling these synchronously though.  - https://github.com/ProjectEvergreen/greenwood/issues/1783
1. [ ] Once the above is place, we can then add support for Deno specific custom loaders on top of that implementation (we should double check that the #1323 can also support this design).
    - We will want to make sure Greenwood init supports Deno
    - This will also require a documentation PR to the website and call outs for version (>2.x and _denoc.json_ config file, `deno install`) 

> Not sure if any of this will help with #1439 ?

**Deno Deploy Support**
1. [x] Rollup Support - https://github.com/ProjectEvergreen/greenwood/issues/1785
    - Should add built-in prefixing of all Node APIs with the `node:` prefix (just do this in core since I know [Cloudflare will also need this](https://github.com/ProjectEvergreen/greenwood/issues/1143#issuecomment-3315249759))
    - ~~rollup config is not passing custom rollup plugins to SSR and API route configs (but we also need to filter out Greenwood default plugins like terser from mangling input sources, like WCC)~~ - not needed as we are making `node:` prefixing part of core
    - should also do https://github.com/ProjectEvergreen/greenwood/issues/1391
1. [ ] Create Deno Deploy adapter
    - denoc.json configuration (static vs dynamic)
    - do we also need deno export conditions?
    - Will need website documentation for this
    - Update our dedicated demo repo - https://github.com/ProjectEvergreen/greenwood-demo-adapter-deno-deploy
    - Account for Lit SSR bundling issues

> 🚨 _Deno Deploy does not [support `unstable-*` APIs](https://github.com/thescientist13/greenwood-deno/pull/3), like the ones needed for [CSS Module Scripts](https://docs.deno.com/runtime/fundamentals/modules/#import-attributes), so this will be temporary gap that we need to call out._

**Deno Lit SSR**
Got a demo of this working here - https://github.com/thescientist13/greenwood-deno/pull/11

Of observation, is that because Deno Deno deploy requires a single server entry point, bundling in all SSR pages / routes would cause issues with [`customElements.define` calls](https://github.com/thescientist13/greenwood-deno/pull/11#issuecomment-5217829050) since multiple of these pages could import the same custom element definition and this would yield an error because it's all in the same bundle.

So for Lit SSR docs, we should call this out in that when using Deno Deploy, developers should either
- opt-in to `isolation` mode in Greenwood (with a little overhead)
- guard the define call themselves, e.g.
    ```ts
     if (!customElements.get("app-card")) {
      customElements.define("app-card", Card);
    }
    ```
