### ISSUE TITLE
v0.31.0 release tracking

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#1328]
## Candidate Issues

1. [x] https://github.com/ProjectEvergreen/greenwood/issues/1183
    - https://github.com/ProjectEvergreen/greenwood/issues/1218
1. [x] https://github.com/ProjectEvergreen/greenwood/issues/1317
    - https://github.com/ProjectEvergreen/greenwood/issues/1309
    - https://github.com/ProjectEvergreen/greenwood/issues/1310
    - https://github.com/ProjectEvergreen/greenwood/issues/684
    - https://github.com/ProjectEvergreen/greenwood/issues/1313
1. [x] https://github.com/ProjectEvergreen/greenwood/issues/1313
    - https://github.com/ProjectEvergreen/greenwood/issues/684
1. [x] https://github.com/ProjectEvergreen/greenwood/issues/1319
1. [x] https://github.com/ProjectEvergreen/greenwood/issues/1320
    - (nice to have) https://github.com/ProjectEvergreen/greenwood/issues/1325
1. [x] https://github.com/ProjectEvergreen/greenwood/issues/1202
    - https://github.com/ProjectEvergreen/greenwood/issues/1220
    - https://github.com/ProjectEvergreen/greenwood/pull/1330
1. [x] 🚨 Windows Loader based GitHub Actions started getting super flaky in https://github.com/ProjectEvergreen/greenwood/pull/1373#issuecomment-2585391696 (works fine locally)
1. [x] https://github.com/ProjectEvergreen/greenwood/pull/1340
1. [ ] (nice to have) https://github.com/ProjectEvergreen/greenwood/pull/1308
1. [ ] (🙅  blocked) https://github.com/ProjectEvergreen/greenwood/issues/1143
    - https://github.com/ProjectEvergreen/greenwood/issues/1324
1. [x] bump all `peerDependencies` on **@greenwood/cli** in all packages to `^0.31.0` - https://github.com/ProjectEvergreen/greenwood/pull/1399
1. [x] Community items we can close out
    - https://github.com/ProjectEvergreen/greenwood/discussions/1339#discussioncomment-11485825
    - https://github.com/ProjectEvergreen/greenwood/discussions/1301
1. [x] Update GitHub Actions version check(s) to only check for Node `20` / `22` actions

## Changelog

https://github.com/ProjectEvergreen/greenwood/issues?q=label%3Av0.31.0+

1. [v0.31.0-alpha.0](https://github.com/ProjectEvergreen/greenwood/releases/tag/v0.31.0-alpha.0)
1. [v0.31.0-alpha.1](https://github.com/ProjectEvergreen/greenwood/releases/tag/v0.31.0-alpha.1)
1. [v0.31.0-alpha.2](https://github.com/ProjectEvergreen/greenwood/releases/tag/v0.31.0-alpha.2)
1. [v0.31.0-alpha.3](https://github.com/ProjectEvergreen/greenwood/releases/tag/v0.31.0-alpha.3)
1. [v0.31.0-alpha.4](https://github.com/ProjectEvergreen/greenwood/releases/tag/v0.31.0-alpha.4)
1. [v0.31.0-alpha.5](https://github.com/ProjectEvergreen/greenwood/releases/tag/v0.31.0-alpha.5)
1. [v0.31.0-alpha.6](https://github.com/ProjectEvergreen/greenwood/releases/tag/v0.31.0-alpha.6)

## Documentation Issues

https://github.com/ProjectEvergreen/www.greenwoodjs.dev/pulls?q=is%3Apr+is%3Aopen+label%3Arelease%2Fv0.31.0

1. [x] https://github.com/ProjectEvergreen/www.greenwoodjs.dev/pull/153
1. [x] https://github.com/ProjectEvergreen/www.greenwoodjs.dev/pull/148
1. [x] https://github.com/ProjectEvergreen/www.greenwoodjs.dev/pull/152
1. [x] https://github.com/ProjectEvergreen/www.greenwoodjs.dev/pull/154
1. [x] https://github.com/ProjectEvergreen/www.greenwoodjs.dev/pull/155
1. [x] https://github.com/ProjectEvergreen/www.greenwoodjs.dev/pull/157
1. [x] https://github.com/ProjectEvergreen/www.greenwoodjs.dev/pull/159
1. [x] ~~v0.31.0 blog post?~~ - no new real features to speak of

## Release Test Plan
Key ecosystem projects to validate this release line with: 
1. [x] ✅   [www.greenwoodjs.dev](https://github.com/ProjectEvergreen/www.greenwoodjs.dev) - https://github.com/ProjectEvergreen/www.greenwoodjs.dev/pull/146
1. [x] ✅ [greenwood-demo-adapter-vercel](https://github.com/ProjectEvergreen/greenwood-demo-adapter-vercel) - https://github.com/ProjectEvergreen/greenwood-demo-adapter-vercel/pull/31
1. [x] ✅ [greenwood-demo-adapter-netlify](https://github.com/ProjectEvergreen/greenwood-demo-adapter-netlify) - https://github.com/ProjectEvergreen/greenwood-demo-adapter-netlify/pull/25
1. [x] ❓ / ⚠️  [thegreenhouse.io](https://github.com/thegreenhouseio/www.thegreenhouse.io) - https://github.com/thegreenhouseio/www.thegreenhouse.io/pull/299
1. [x] ✅ [contributary.community](https://github.com/ContributaryCommunity/www.contributary.community) - https://github.com/ContributaryCommunity/www.contributary.community/pull/126
1. [x] ✅  [analogstudios.net](https://github.com/AnalogStudiosRI/www.analogstudios.net) - https://github.com/AnalogStudiosRI/www.analogstudios.net/pull/100
1. [x] ✅    [tuesdaystunes.tv](https://github.com/AnalogStudiosRI/www.tuesdaystunes.tv) - https://github.com/AnalogStudiosRI/www.tuesdaystunes.tv/pull/132
1. [x] ✅  [blissri.com](https://github.com/AnalogStudiosRI/www.blissri.com) - https://github.com/AnalogStudiosRI/www.blissri.com/pull/55
1. [x] ✅  [greenwood-getting-started](https://github.com/ProjectEvergreen/greenwood-getting-started) - https://github.com/ProjectEvergreen/greenwood-getting-started/pull/89
1. [x] ✅ [greenwood-starter-presentation](https://github.com/thescientist13/greenwood-starter-presentation) - https://github.com/thescientist13/greenwood-starter-presentation/pull/73
1. [x] ✅  [greenwood-demo-github-pages](https://github.com/ProjectEvergreen/greenwood-demo-github-pages) - https://github.com/ProjectEvergreen/greenwood-demo-github-pages/pull/8
1. [x] ✅  [greenwood-lit-ssr](https://github.com/thescientist13/greenwood-lit-ssr) - https://github.com/thescientist13/greenwood-lit-ssr/pull/21
1. [x] ✅ [greenwood-htmx](https://github.com/thescientist13/greenwood-htmx) - https://github.com/thescientist13/greenwood-htmx/pull/18
1. [x] ✅  [greenwood-demo-platform-docker](https://github.com/ProjectEvergreen/greenwood-demo-platform-docker) - https://github.com/ProjectEvergreen/greenwood-demo-platform-docker/pull/8
1. [x] ✅  [greenwood-demo-adapter-aws](https://github.com/ProjectEvergreen/greenwood-demo-adapter-aws) - https://github.com/ProjectEvergreen/greenwood-demo-adapter-aws/pull/4
1. [x] ✅  [greenwood-demo-adapter-cloudflare](https://github.com/ProjectEvergreen/greenwood-demo-adapter-cloudflare) - https://github.com/ProjectEvergreen/greenwood-demo-adapter-cloudflare/pull/6
1. [x] ✅ `npx @greenwood/init@alpha`
1. [x] ✅  https://github.com/lschierer/HP_Stuff/pull/2
1. [x] ✅  Stackblitz

**Comment by thescientist13** [comment]
The release is out!
https://github.com/ProjectEvergreen/greenwood/releases/tag/v0.31.0
