### ISSUE TITLE
final release and questions checklist

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#428]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
As part of #355 and #418 , here are some low hanging things to track.

## Details
1. [x] Keep **colors** package? - might be a good issue to back in if we can do it internally
1. [x] Make sure communicate Node v12 minimum dependency
1. [x] Is a _theme.css_ still needed now from the CLI specifically? - No
1. [x] Make sure all TODOs / lifecycles are addressed and code is cleaned up
1. [x] Rollup refactoring TODOs
1. [x] use only named exports for plugins - will make a discussion
1. [x] delete _templates/_ dir - N/A
1. [x] Make sure all tests are re-enabled
    - markdown + code examples
    - revisit smoke tests (hello?) / consolidate / put in default? / 404
    - `describe.only` / `it.only` / `xit` 
    - make sure all tests are deleted or turned on
    - enable `checkCoverage` / `include` config
    - unit tests for transforms
    - eject
    - replace `beforeEach` w/ `beforeAll`
1. [x] Alpha testing in getting started and www.thegreenhouse.io
1. [x] import maps as a plugin?  or default for now, should check caniuse.com
1. [x] final performance and [build time benchmarking](https://twitter.com/slightlylate/status/1335299502652080130)
1. [x] Migration Path (for Release Notes)
     - rename a _<xxx>-template.js_ => _<xxx>.html_
     - before / after for getting started
     - `<entry>` -> `<content-outlet>`
     - use forward slashes for all paths
     - _theme.css_
