### ISSUE TITLE
Determine project sitemap and top / sub level navigations

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#89]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [x] Other (please clarify below)

## Summary
Goal of this ticket is to capture the necessary pages and navigation.

## Details
Needs to make tickets and track
- [x] [Home](#19 ) - Splash / marketing page, getting started links, quick start?
- [x] [About](#97) - Project overview and philosophy
  1. Roadmap - General roadmap (pull from GitHub)
  1. Community - Other projects / teams to follow in the ecosystem
- [x] [Getting Started](#98) - A project starter walk through. See documentation for all possibilities!
  1. System Requirements / Prerequisites  - NodeJS, npm / yarn, git?
  1. Installing Greenwood
  1. Project Structure - importance of using directories, .e.g #85 
  1. Development
  1. Creating a page / pages
  1. Setting some configuration
  1. Creating a custom page template
  1. Building for Production / Deployment
- [x] [Documentation](https://github.com/ProjectEvergreen/greenwood/issues/20) - Usage, Configuration, and APIs
  1. Configuration - All options and what they mean
  1. Markdown - Markdown for content, link to cheatsheet, examples
  1. Component Model - How to use Web Components
  1. Templates - Page and App Templates
  1.  Front Matter - Options and capabilities 
  1. Tech stack - Insight into the technologies used?
